### ISSUE TITLE
Implement dropzone in document uploader

### ISSUE THREAD

**Issue by landonwjohnson** [bridgefinancial/bridge-nextjs#98]
### Feature Description

url
https://app.bridge.financial/portal/documents

Documents need to be able to be dragged and dropped 

![image](https://github.com/user-attachments/assets/9ca8db71-36f8-43cf-942b-234cdf97a699)

---

### Purpose

Is this feature focused on project completion or solving a user problem?

- [x] Project completion  
      <small>Getting the feature ready for launch.</small>

- [x] Solving a specific user problem  
      <small>Addressing a challenge faced by users.</small>

---

### Key Requirements

What is the main goal of this feature? (Select all that apply)

- [x] Ensure the feature is ready for release  
      <small>Make the feature launch-ready.</small>

- [x] Add a new feature  
      <small>Introduce a new functionality.</small>

---

### Success Criteria

How will we know if this feature is successful? (Select all that apply)

- [x] The feature is complete and meets project goals  
      <small>Achieves the intended objectives.</small>

---

### Platform

Which platform does this feature impact? (Select one):

- [x] 🌐 **Web**  
      <small>Affects browser-based platforms.</small>

---

### Priority

Please select the priority of this feature:

- [x] 🚨 **Priority: Critical**  
      <small>Must be completed immediately.</small>

---

### Story Points

Select story points based on the effort, complexity, and risk of the task:

- [x] ⏳ **Story Points: 5**  
      <small>Moderate effort, some complexity or dependencies.</small>

---

### Task Difficulty

Please select the difficulty level for this task:

- [x] 👍 **Difficulty: Easy**  
      <small>Requires minimal effort and complexity.</small>

---

#### Proposed Implementation Steps:

1. **Step 1**: look into html on drop methods, possible react drag and drop (react drag and drop will probably not be needed)
2. **Step 2**: Implement it in storybook and test out the functionality 
3. **Step 3**: Be sure it works on the documents page
